version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=redis
      - CACHE_STORE=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - track-me-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - track-me-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  track-me-network:
    driver: bridge